### ISSUE TITLE
The operator keeps sending `update` requests to vault even though nothing has changed

### ISSUE THREAD

**Issue by ameyp** [redhat-cop/vault-config-operator#104] opened 2023-01-05 23:21 UTC
I don't know whether this is happening for multiple resource types, but I'm seeing it for at least `policy` objects.

1. The operator sends a request to vault to `read` a policy
2. Vault responds with the policy's `name` and `rules`
3. The operator sends a request to vault to `update` the policy
4. Vault responds with 202

This process repeats every 2-5 seconds.

Vault version 1.11.2

**Comment by raffaelespazzoli** [comment] 2023-01-06 13:13
this typically happens when this function https://github.com/redhat-cop/vault-config-operator/blob/ce058305b778fadedcf40193f0c3553d29c5a989/api/v1alpha1/policy_types.go#L41 stops working. 
It's possible that the vault API have changed and this function does not work correctly anymore. Would you have time to test it.

**Comment by ameyp** [comment] 2023-01-06 17:21
Thanks for the pointer, I'll test it this weekend

**Comment by ameyp** [comment] 2023-01-10 07:05
Tested it, that's definitely the problem. I dumped `payload` as well as `d.GetPayload()`, here's the difference:

Expected (`d.GetPayload()`):

```
name => my-test-policy
rules => path "secrets/*" {
  capabilities = ["read", "list"]
}
```

Actual (`payload`):

```
policy => path "logins/*" {
  capabilities = ["read", "list"]
}
```

This is with Vault version 1.12.0.

**Comment by raffaelespazzoli** [comment] 2023-01-13 18:52
I am looking at this. not sure what to do. The doc seem to indicate that the result should have `policy` has the key not `rules`.

**Comment by raffaelespazzoli** [comment] 2023-01-13 18:54
https://developer.hashicorp.com/vault/api-docs/system/policies#read-acl-policy

**Comment by ameyp** [comment] 2023-01-13 19:03
Could it be my setup somehow? Were you able to verify it locally?

**Comment by raffaelespazzoli** [comment] 2023-01-13 19:38
no I was able to reproduce it, but still not sure what to do. Also because if input keys are not equals to output keys in the map, the entire logic on which the operator is built has to be thrown away. So I need to understand, is this a bug, an exception or a the new normal?

**Comment by ameyp** [comment] 2023-01-13 21:33
Wait, I'm confused. As I described in https://github.com/redhat-cop/vault-config-operator/issues/104#issuecomment-1376819111, the response obtained from vault (actual payload) has the key `policy`, which is what the documentation says it should have. The operator on the other hand expects the response to contain the keys `name` and `rules` (expected payload).

Apologies if I was unclear with respect to what is `actual` and what is `expected`. Here's how I'm printing both:

```
func (d *Policy) IsEquivalentToDesiredState(payload map[string]interface{}) bool {
	isEqual := reflect.DeepEqual(d.GetPayload(), payload)
	log.Log.Info(fmt.Sprintf("Checking isEquivalent for %s: %v", d.GetPath(), isEqual))
	for k, v := range payload {
		log.Log.Info(fmt.Sprintf("Expect %v => %v", k, v))
	}
	for k, v := range d.GetPayload() {
		log.Log.Info(fmt.Sprintf("Actual %v => %v", k, v))
	}

	return isEqual
}
```

**Comment by ameyp** [comment] 2023-01-13 21:37
I made a `curl` request, and the response from vault does match the documentation:

```
{
  "request_id": "cf1c7715-b76c-8ea9-3235-9912e1020194",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "name": "operator",
    "policy": "<REDACTED>"
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}

```

**Comment by ameyp** [comment] 2023-01-13 21:56
However, the `path` being read by the operator for the policy resource is not `/sys/policies/acl`, it is `/sys/policy`, and the response for that endpoint matches the documentation

https://developer.hashicorp.com/vault/api-docs/system/policy#read-policy

**Comment by raffaelespazzoli** [comment] 2023-01-14 01:33
I tested the changing the API policy and it works. It should have never worked with the wrong path, so this should be fixed, but changing this will have implications as i actually changes the path of the policy. Please close you PR, I'll have one that is more comprehensive.

**Comment by ameyp** [comment] 2023-01-14 01:58
Sounds good, closed my PR

**Comment by raffaelespazzoli** [comment] 2023-01-14 02:04
I verified that kubernetes authentication engine roles based on policies created the previous way stop working with the change of path. So this would be a breaking change. I really would like to be able to talk to someone at hashicorp about this.

**Comment by raffaelespazzoli** [comment] 2023-01-14 12:56
the impact is that you everywhere you where referencing a policy, now you need to prepend `acl/<policy-name>`

**Comment by ameyp** [comment] 2023-01-14 16:56
To maintain backwards compatibility, we could instead do this:

- Change the controller to check for `rules` for the `Policy` resource type (instead of checking for `policy`) and also mark it as `Deprecated` in some way
- Add a new `AclPolicy` resource type that uses the `sys/policies/acl` endpoint
- At some point down the line, remove support for the `Policy` resource type

**Closed** 2023-02-06 14:52 UTC
